"""Progress report: the level-test history in vocab/tests/ → the generated block of vocab/progress.md.
GitHub issue nhanpc/DET#9 (Phase 4). Pure functions: build() makes one dict from the loaded sessions and
levels.csv rows, render_markdown() turns it into text, splice() puts that text between the two markers of
progress.md. scripts/report.py does the I/O; main.py serves the same dict as GET /api/progress and builds
the Learn page from it, so the report and the app cannot disagree.

Everything comes from vocab/tests/ (sessions/*.json, levels.csv, mocks.csv): the hand-written half of
progress.md is never parsed. Mock tests (issue #11, Phase 6) are the hand-typed mocks.csv rows: parse_mocks()
validates them, mock_rows() keeps the last row per date and source, mock_focus() picks next week's drill
focus, mock_verdict() answers "book the real test yet?" — the *Mock tests* section after **Anki**.
"""
from __future__ import annotations

import sqlite3
from datetime import date, datetime, timedelta
from typing import Optional

from . import learn
from .bank import Subband

START = "<!-- generated:start -->"
END = "<!-- generated:end -->"
HEADING = "## Progress (generated)"
GENERATED = "_Generated by scripts/report.py on {date} from vocab/tests/. Do not edit._"
STUB = "# Progress\n\nHand-written baseline goes above the markers: see issue #7.\n"   # a missing progress.md
TARGET = 120                # the DET score the chart title points at
MATURE = 21                 # Anki: a card with an interval of this many days or more is mature
REVIEW_DAYS = 7             # Anki: the review-count window
DASH = "—"
# Mock tests (#11): the four subscores in README order — the focus tie-break — and each one's drill folders
SUBSCORES = ("literacy", "comprehension", "conversation", "production")
FOLDERS = {"literacy": ["read-and-complete/", "writing/"],                                   # R + W
           "comprehension": ["read-and-complete/", "listen-and-type/", "interactive/"],      # R + L
           "conversation": ["listen-and-type/", "speaking/"],                                # L + S
           "production": ["writing/", "speaking/"]}                                          # W + S
OFFICIAL = "official"       # `source` of a certified test: shown in bold, gates `Goal reached`, never the booking verdict
SCALE = range(10, 161, 5)   # the DET scale: 10–160 in steps of 5
SUBSCORE_DAYS = 28          # subscores older than this (before the latest mock) no longer pick the focus
MOCK_DAYS = 14              # no mock within this many days before `generated` → mock overdue


def det_range(low: Optional[int], high: Optional[int]) -> str:
    """`60–85`, or `120+` at the top of the scale — the same text the app shows."""
    if low is None:
        return DASH
    return f"{low}+" if high is not None and high >= 160 else f"{low}–{high}"


def level_series(history: list[dict], by: dict[str, Subband]) -> list[dict]:
    """One chart point per day: the day's last reliable test that has a level, y = Subband.order."""
    days: dict[str, dict] = {}
    for h in history:
        if h["reliable"] and h["level"] in by:
            days[h["date"]] = {"date": h["date"], "session": h["session"], "order": by[h["level"]].order,
                               "level": h["level"]}
    return [days[d] for d in sorted(days)]


def parse_mocks(rows: list[dict]) -> list[dict]:
    """mocks.csv rows (strings, store.load_mocks()) → typed rows in file order: scores int or None, `weakest`
    "" or a SUBSCORES name. A bad row raises ValueError naming its line (the header is line 1): `date` not
    YYYY-MM-DD, `source` empty, `overall` missing or any score not a multiple of 5 in 10–160, `weakest` not a
    subscore name. Nothing is skipped — the report stops instead of hiding a typo."""
    out = []
    for n, r in enumerate(rows, start=2):
        cell = lambda k: (r.get(k) or "").strip()                                          # noqa: E731

        def score(k: str) -> Optional[int]:
            v = cell(k)
            if not v and k != "overall":
                return None
            if not v.isdigit() or int(v) not in SCALE:
                raise ValueError(f"line {n}: {k} = {v!r}, expected a multiple of 5 in 10–160")
            return int(v)

        try:
            if len(cell("date")) != 10:                     # fromisoformat also takes 20260920 on 3.11+
                raise ValueError
            day = date.fromisoformat(cell("date"))
        except ValueError:
            raise ValueError(f"line {n}: date = {cell('date')!r}, expected YYYY-MM-DD") from None
        if not cell("source"):
            raise ValueError(f"line {n}: source is empty")
        if cell("weakest") and cell("weakest") not in SUBSCORES:
            raise ValueError(f"line {n}: weakest = {cell('weakest')!r}, expected one of {', '.join(SUBSCORES)} or blank")
        out.append({"date": day.isoformat(), "source": cell("source"), "overall": score("overall"),
                    **{k: score(k) for k in SUBSCORES}, "weakest": cell("weakest"), "notes": cell("notes")})
    return out


def mock_rows(parsed: list[dict]) -> list[dict]:
    """The last row per date and source (a same-day retake replaces the earlier one; an `official` row never
    replaces a practice row), by date, file order within a day — the rows every mock rule runs on."""
    last: dict[tuple[str, str], dict] = {}
    for r in parsed:
        last.pop((r["date"], r["source"]), None)
        last[(r["date"], r["source"])] = r
    return sorted(last.values(), key=lambda r: r["date"])


def mock_dates(rows: list[dict], practice_only: bool = False) -> list[tuple[str, int]]:
    """(date, overall) per date, oldest first; two sources on one day count once, with the lower overall."""
    by: dict[str, int] = {}
    for r in rows:
        if not (practice_only and r["source"] == OFFICIAL):
            by[r["date"]] = min(by.get(r["date"], r["overall"]), r["overall"])
    return sorted(by.items())


def has_subscores(r: dict) -> bool:
    return all(r[s] is not None for s in SUBSCORES)


def mock_focus(rows: list[dict]) -> dict:
    """Next week's extra drill slot: {"subscore", "folders", "reason"}. 1. The lowest subscore of the latest row
    that has all four, if it is ≤ SUBSCORE_DAYS before the latest row — a tie goes to the one that dropped most
    since the previous row with subscores, then to SUBSCORES order. 2. Else the latest row's `weakest`.
    3. Else vocabulary (subscore None): `no mocks` without rows, `no weakest` when the latest has neither."""
    if not rows:
        return {"subscore": None, "folders": [], "reason": "no mocks"}
    latest, full = rows[-1], [r for r in rows if has_subscores(r)]
    if full and (date.fromisoformat(latest["date"]) - date.fromisoformat(full[-1]["date"])).days <= SUBSCORE_DAYS:
        r, prev = full[-1], full[-2] if len(full) > 1 else None
        low = [s for s in SUBSCORES if r[s] == min(r[s] for s in SUBSCORES)]
        if len(low) > 1 and prev:
            drop = {s: prev[s] - r[s] for s in low}
            low = [s for s in low if drop[s] == max(drop.values())]
        return {"subscore": low[0], "folders": FOLDERS[low[0]], "reason": f"subscores of {r['date']}"}
    if latest["weakest"]:
        return {"subscore": latest["weakest"], "folders": FOLDERS[latest["weakest"]], "reason": "weakest column"}
    return {"subscore": None, "folders": [], "reason": "no weakest"}


def mock_verdict(rows: list[dict]) -> tuple[str, Optional[int]]:
    """Book the real test yet? (verdict, gap). `Goal reached` on any official row ≥ TARGET; the rest on the
    practice dates of mock_dates(): `Book the real test` when the last two are ≥ TARGET, `one more ≥ 120 to
    book` when only the last is (or there is only one), else `keep going` with the gap TARGET − last overall."""
    if any(r["source"] == OFFICIAL and r["overall"] >= TARGET for r in rows):
        return "Goal reached", None
    dates = mock_dates(rows, practice_only=True)
    if not dates:
        return "keep going", None
    if dates[-1][1] < TARGET:
        return "keep going", TARGET - dates[-1][1]
    if len(dates) > 1 and dates[-2][1] >= TARGET:
        return "Book the real test", None
    return f"one more ≥ {TARGET} to book", None


def mocks_report(mocks: list[dict], history: list[dict], today: date) -> dict:
    """The `mocks` key of build(): the de-duplicated rows (+ `vocab`, the DET range of the latest reliable level
    test on or before the mock), the chart series (one point per date), the trend of the last two dates (the
    level_history() rule), `overdue`, the focus and the verdict. Raises ValueError on a bad row."""
    rows = mock_rows(parse_mocks(mocks))
    reliable = [h for h in history if h["reliable"] and h["det_low"] is not None]
    for r in rows:
        prior = [h for h in reliable if h["date"] <= r["date"]]
        r["vocab"] = det_range(prior[-1]["det_low"], prior[-1]["det_high"]) if prior else ""
    dates = mock_dates(rows)
    last = [o for _, o in dates[-2:]]
    trend = "" if len(last) < 2 else "up" if last[1] > last[0] else "down" if last[1] < last[0] else "flat"
    overdue = not rows or date.fromisoformat(rows[-1]["date"]) < today - timedelta(days=MOCK_DAYS)
    verdict, gap = mock_verdict(rows)
    return {"rows": rows, "series": [{"date": d, "overall": o} for d, o in dates], "trend": trend,
            "overdue": overdue, "focus": mock_focus(rows), "verdict": verdict, "gap": gap}


def build(sessions: list[dict], levels: list[dict], subbands: list[Subband], today: Optional[date] = None,
          mocks: Optional[list[dict]] = None) -> dict:
    """The report: pooled level and frontier (learn.frontier), the sub-band rows, the word-status counts, the
    chart series and the mock tests (mocks_report() on `mocks`, the store.load_mocks() rows; None = no rows).
    `anki` stays None; scripts/report.py fills it from anki_stats() when asked."""
    by = {sb.name: sb for sb in subbands}
    scores = learn.subband_scores(sessions, subbands)
    level, front = learn.frontier(scores)
    history, trend = learn.level_history(levels)
    reliable = [h for h in history if h["reliable"]]
    sb = by.get(level) if level else None
    rows = [{"subband": s["subband"], "cefr": by[s["subband"]].cefr,
             "det": det_range(by[s["subband"]].det_low, by[s["subband"]].det_high), **s} for s in scores]
    today = today or date.today()
    return {"generated": today.isoformat(),
            "tests": len(history), "reliable_tests": len(reliable),
            "no_level": sum(1 for h in reliable if h["level"] is None),      # reliable, but nothing mastered
            "level": level, "frontier": front, "last_level": reliable[-1]["level"] if reliable else None,
            "cefr": sb.cefr if sb else None, "det_low": sb.det_low if sb else None,
            "det_high": sb.det_high if sb else None, "trend": trend,
            "subbands": rows, "counts": learn.status_counts(learn.word_stats(sessions)),
            "series": level_series(history, by), "anki": None,
            "mocks": mocks_report(mocks or [], history, today)}


def now_line(r: dict) -> str:
    """`Level 3k-b (B1) · DET ≈ 60–85 · frontier 4k-a · trend up · 3 tests (3 reliable) · last test 4k-a`."""
    parts = [f"Level {r['level']} ({r['cefr']}) · DET ≈ {det_range(r['det_low'], r['det_high'])}" if r["level"]
             else "No level yet", f"frontier {r['frontier']}"]
    if r["trend"]:
        parts.append(f"trend {r['trend']}")
    parts.append(f"{r['tests']} test{'s' if r['tests'] != 1 else ''} ({r['reliable_tests']} reliable)")
    if r["last_level"] != r["level"]:
        parts.append(f"last test {r['last_level'] or 'no level'}")
    return " · ".join(parts)


def table(header: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def chart(series: list[dict], subbands: list[Subband]) -> str:
    """Mermaid xychart of `series` as is: x = one label per day (`15 Sep`), y = sub-band index."""
    goal = next((sb for sb in subbands if sb.det_low >= TARGET), subbands[-1])
    labels = ", ".join(f'"{date.fromisoformat(p["date"]).strftime("%-d %b")}"' for p in series)
    return "\n".join(["```mermaid", "xychart-beta",
                      f'    title "Level over time (1 = {subbands[0].name} … {len(subbands)} = {subbands[-1].name}; '
                      f'{goal.order} = {goal.cefr} / DET {TARGET})"',
                      f"    x-axis [{labels}]", f'    y-axis "Sub-band" 1 --> {len(subbands)}',
                      f"    line [{', '.join(str(p['order']) for p in series)}]", "```"])


def mock_chart(series: list[dict]) -> str:
    """Mermaid xychart of the overall score per date (`09-20` labels) with a flat TARGET line for the gap."""
    lo = min(60, min(p["overall"] for p in series) // 10 * 10)
    labels = ", ".join(f'"{p["date"][5:]}"' for p in series)
    return "\n".join(["```mermaid", "xychart-beta", '    title "Mock tests: overall"', f"    x-axis [{labels}]",
                      f'    y-axis "DET" {lo} --> {SCALE[-1]}', f"    line [{', '.join(str(p['overall']) for p in series)}]",
                      f"    line [{', '.join([str(TARGET)] * len(series))}]", "```"])


def mock_lines(m: dict, frontier: str) -> list[str]:
    """The *Mock tests* section body: the chart and the table when there are rows (official rows in bold, `←`
    on the lowest subscore of a row that has all four), then the trend (+ `mock overdue`), the focus with its
    reason and the booking verdict."""
    md = []
    if m["rows"]:
        lines = []
        for r in m["rows"]:
            low = min(r[s] for s in SUBSCORES) if has_subscores(r) else None
            cells = [r["date"], r["source"], r["overall"],
                     *["" if r[s] is None else f"{r[s]} ←" if r[s] == low else r[s] for s in SUBSCORES],
                     r["weakest"], r["vocab"]]
            lines.append([f"**{c}**" if c != "" and r["source"] == OFFICIAL else c for c in cells])
        md += [mock_chart(m["series"]), "", table(["Date", "Source", "Overall", *[s.capitalize() for s in SUBSCORES],
                                                   "Weakest", "Vocab"], lines), ""]
    else:
        md += ["_No mock yet — take the free practice test and type it as row 1 of vocab/tests/mocks.csv._", ""]
    f = m["focus"]
    focus = f"{f['subscore'].capitalize()} → {', '.join(f['folders'])}" if f["subscore"] else f"vocabulary → {frontier}"
    verdict = m["verdict"] if m["gap"] is None else f"{m['verdict']} (gap {m['gap']})"
    if m["verdict"] in ("Goal reached", "Book the real test"):
        verdict = f"**{verdict}**"
    return md + [f"- Trend: {m['trend'] or DASH}" + (" · mock overdue" if m["overdue"] else ""),
                 f"- Focus next week: {focus} ({f['reason']})", f"- Booking: {verdict}"]


def render_markdown(r: dict, subbands: list[Subband]) -> str:
    """Everything between the markers, HEADING first, in the order fixed in #9, then the *Mock tests* section
    of #11 after **Anki**. Ends with a newline."""
    md = [HEADING, GENERATED.format(date=r["generated"]), "", "### Now", "", now_line(r), "", "### Sub-bands", ""]
    pct = lambda x: f"{100 * x:.0f} %" if x is not None else DASH                          # noqa: E731
    md.append(table(["Sub-band", "CEFR", "DET", "Blocks", "Known", "Score", "Status"],
                    [[s["subband"], s["cefr"], s["det"], s["blocks"], pct(s["known"]),
                      f"{s['score']:.2f}" if s["score"] is not None else DASH,
                      s["status"] + (" ← frontier" if s["subband"] == r["frontier"] else "")] for s in r["subbands"]]))
    c = r["counts"]
    md += ["", "### Words", "", " · ".join(f"{k} {c[k]}" for k in learn.STATUSES) + f" ({c['seen']} seen)",
           "", "### Level over time", ""]
    if r["series"]:
        md += [chart(r["series"], subbands), "",
               table([str(sb.order) for sb in subbands], [[sb.name for sb in subbands]])]
    else:
        md.append("_No reliable test with a level yet — the chart starts with the first one._")
    # the footnote: tests the chart leaves out (unreliable, no level, or an earlier test on a plotted day)
    unreliable, no_level = r["tests"] - r["reliable_tests"], r["no_level"]
    same_day = r["reliable_tests"] - no_level - len(r["series"])
    left = [f"{n} {what}" for n, what in ((unreliable, "unreliable"), (no_level, "without a level"),
                                          (same_day, "earlier on a day with more than one test")) if n]
    if left:
        md += ["", f"_Not on the chart: {', '.join(left)}._"]
    if r["anki"] is not None:
        md += ["", "### Anki", ""]
        md.append(table(["Sub-band", "Cards", "Mature", f"Reviews {REVIEW_DAYS}d", "Lapses"],
                        [[a["subband"], a["cards"], a["mature"], a["reviews"], a["lapses"]] for a in r["anki"]])
                  if r["anki"] else "_No cards tagged with a sub-band yet._")
    md += ["", "### Mock tests", "", *mock_lines(r["mocks"], r["frontier"])]
    return "\n".join(md) + "\n"


def splice(text: str, generated: str) -> str:
    """`text` with everything strictly between START and END replaced by `generated` (the #7 rule table).
    Both markers missing → a blank line, the markers and the block are appended, the text above untouched.
    One marker missing, a marker repeated, or END before START → ValueError (the script exits 1)."""
    lines = text.split("\n")
    starts = [i for i, l in enumerate(lines) if l == START]
    ends = [i for i, l in enumerate(lines) if l == END]
    block = [START, *generated.strip("\n").split("\n"), END]
    if not starts and not ends:
        head = text if not text or text.endswith("\n") else text + "\n"
        return head + ("\n" if head else "") + "\n".join(block) + "\n"
    if len(starts) != 1 or len(ends) != 1:
        raise ValueError(f"needs exactly one {START} and one {END} line, each alone on its line "
                         f"(found {len(starts)} and {len(ends)})")
    if ends[0] < starts[0]:
        raise ValueError(f"{END} comes before {START}")
    return "\n".join([*lines[: starts[0]], *block, *lines[ends[0] + 1:]])


def anki_stats(conn: sqlite3.Connection, subbands: list[Subband], now: Optional[datetime] = None) -> list[dict]:
    """Per sub-band, from a copy of Anki's collection.anki2: cards whose note carries the sub-band as a tag
    (export_anki() writes `<subband> <reason>`; Anki splits it into two tags), of which mature, reviews in the
    last REVIEW_DAYS days and lapses. Only sub-bands with cards, in subbands.csv order."""
    since = int(((now or datetime.now()) - timedelta(days=REVIEW_DAYS)).timestamp() * 1000)
    reviews = dict(conn.execute("SELECT cid, COUNT(*) FROM revlog WHERE id >= ? GROUP BY cid", (since,)))
    names = {sb.name for sb in subbands}
    agg: dict[str, dict] = {}
    for cid, tags, ivl, lapses in conn.execute("SELECT c.id, n.tags, c.ivl, c.lapses FROM cards c JOIN notes n ON n.id = c.nid"):
        for tag in set(tags.split()) & names:
            a = agg.setdefault(tag, {"subband": tag, "cards": 0, "mature": 0, "reviews": 0, "lapses": 0})
            a["cards"] += 1
            a["mature"] += ivl >= MATURE
            a["reviews"] += reviews.get(cid, 0)
            a["lapses"] += lapses
    return [agg[sb.name] for sb in subbands if sb.name in agg]


def check(sessions: list[dict], levels: list[dict], results: list[dict]) -> list[str]:
    """Disagreements between the CSV views and the session JSON (a hand-edited CSV): one line each, empty
    when everything matches. levels.csv: one row per finished session with the same level, blocks and
    reliable flag; results.csv: one row per finished block with the same hits and false alarms."""
    out = []
    by_level = {r["session"]: r for r in levels}
    by_result: dict[str, list[dict]] = {}
    for r in results:
        by_result.setdefault(r["session"], []).append(r)
    for s in sessions:
        if not s.get("finished"):
            continue
        row, res = by_level.get(s["id"]), s["result"]
        if row is None:
            out.append(f"{s['id']}: no levels.csv row")
        else:
            want = {"level": res["level"] or "", "blocks": str(res["blocks"]), "reliable": str(int(res["reliable"]))}
            for k, v in want.items():
                if row[k] != v:
                    out.append(f"{s['id']}: levels.csv {k} = {row[k]!r}, session says {v!r}")
        blocks = [b for b in s["blocks"] if b["pos"] >= len(b["items"])]
        rows = by_result.get(s["id"], [])
        if len(rows) != len(blocks):
            out.append(f"{s['id']}: {len(rows)} results.csv rows, session has {len(blocks)} finished blocks")
        for b, r in zip(blocks, rows):
            if (r["subband"], r["hits"], r["false_alarms"]) != (b["subband"], str(b["hits"]), str(b["false_alarms"])):
                out.append(f"{s['id']} block {b['no']}: results.csv says {r['subband']} {r['hits']}/{r['false_alarms']}, "
                           f"session says {b['subband']} {b['hits']}/{b['false_alarms']}")
    known = {s["id"] for s in sessions}
    out += [f"{r['session']}: levels.csv row without a session file" for r in levels if r["session"] not in known]
    return out
