"""Progress report: the level-test history in vocab/tests/ → the generated block of vocab/progress.md.
GitHub issue nhanpc/DET#9 (Phase 4). Pure functions: build() makes one dict from the loaded sessions and
levels.csv rows, render_markdown() turns it into text, splice() puts that text between the two markers of
progress.md. scripts/report.py does the I/O; main.py serves the same dict as GET /api/progress and builds
the Learn page from it, so the report and the app cannot disagree.

Everything comes from vocab/tests/ (sessions/*.json, levels.csv, mocks.csv): the hand-written half of
progress.md is never parsed. Level, frontier and the DET estimate come from the ability θ (issue #14):
learn.theta_history() replays every session, so sessions from before #14 get a θ too. Mock tests (issue #11, Phase 6) are the hand-typed mocks.csv rows: parse_mocks()
validates them, mock_rows() keeps the last row per date and source, mock_focus() picks next week's drill
focus, mock_verdict() answers "book the real test yet?" — the *Mock tests* section after **Anki**.
"""
from __future__ import annotations

import sqlite3
from datetime import date, datetime, timedelta
from typing import Optional

from . import irt, learn
from .bank import Subband
from .drills import EVENT_KINDS, parse_events

START = "<!-- generated:start -->"
END = "<!-- generated:end -->"
HEADING = "## Progress (generated)"
GENERATED = "_Generated by scripts/report.py on {date} from vocab/tests/. Do not edit._"
STUB = "# Progress\n\nHand-written baseline goes above the markers: see issue #7.\n"   # a missing progress.md
TARGET = 120                # the DET score the chart title points at
MATURE = 21                 # Anki: a card with an interval of this many days or more is mature
REVIEW_DAYS = 7             # Anki: the review-count window
DASH = "—"
# Mock tests (#11): the four subscores in README order — the focus tie-break — and each one's drill folders
SUBSCORES = ("literacy", "comprehension", "conversation", "production")
FOLDERS = {"literacy": ["read-and-complete/", "writing/"],                                   # R + W
           "comprehension": ["read-and-complete/", "listen-and-type/", "interactive/"],      # R + L
           "conversation": ["listen-and-type/", "speaking/"],                                # L + S
           "production": ["writing/", "speaking/"]}                                          # W + S
OFFICIAL = "official"       # `source` of a certified test: shown in bold, gates `Goal reached`, never the booking verdict
SCALE = range(10, 161, 5)   # the DET scale: 10–160 in steps of 5
SUBSCORE_DAYS = 28          # subscores older than this (before the latest mock) no longer pick the focus
MOCK_DAYS = 14              # no mock within this many days before `generated` → mock overdue
KIND_DAYS = 14              # the *Listening* line counts the dictation error kinds of the last two weeks (#16)


def det_range(low: Optional[int], high: Optional[int]) -> str:
    """`60–85`, or `120+` at the top of the scale — the same text the app shows."""
    if low is None:
        return DASH
    return f"{low}+" if high is not None and high >= 160 else f"{low}–{high}"


def theta_series(thetas: list[dict]) -> list[dict]:
    """One chart point per reliable session: date, started, session, theta, se, frontier."""
    return [{"date": h["date"], "started": h["started"], "session": h["id"], "theta": h["theta"], "se": h["se"],
             "frontier": h["frontier"]} for h in thetas if h["reliable"]]


def level_series(history: list[dict], by: dict[str, Subband]) -> list[dict]:
    """One chart point per day: the day's last reliable test that has a level, y = Subband.order (the view
    from before #14, still served under `series`)."""
    days: dict[str, dict] = {}
    for h in history:
        if h["reliable"] and h["level"] in by:
            days[h["date"]] = {"date": h["date"], "session": h["session"], "order": by[h["level"]].order,
                               "level": h["level"]}
    return [days[d] for d in sorted(days)]


def parse_mocks(rows: list[dict]) -> list[dict]:
    """mocks.csv rows (strings, store.load_mocks()) → typed rows in file order: scores int or None, `weakest`
    "" or a SUBSCORES name. A bad row raises ValueError naming its line (the header is line 1): `date` not
    YYYY-MM-DD, `source` empty, `overall` missing or any score not a multiple of 5 in 10–160, `weakest` not a
    subscore name. Nothing is skipped — the report stops instead of hiding a typo."""
    out = []
    for n, r in enumerate(rows, start=2):
        cell = lambda k: (r.get(k) or "").strip()                                          # noqa: E731

        def score(k: str) -> Optional[int]:
            v = cell(k)
            if not v and k != "overall":
                return None
            if not v.isdigit() or int(v) not in SCALE:
                raise ValueError(f"line {n}: {k} = {v!r}, expected a multiple of 5 in 10–160")
            return int(v)

        try:
            if len(cell("date")) != 10:                     # fromisoformat also takes 20260920 on 3.11+
                raise ValueError
            day = date.fromisoformat(cell("date"))
        except ValueError:
            raise ValueError(f"line {n}: date = {cell('date')!r}, expected YYYY-MM-DD") from None
        if not cell("source"):
            raise ValueError(f"line {n}: source is empty")
        if cell("weakest") and cell("weakest") not in SUBSCORES:
            raise ValueError(f"line {n}: weakest = {cell('weakest')!r}, expected one of {', '.join(SUBSCORES)} or blank")
        out.append({"date": day.isoformat(), "source": cell("source"), "overall": score("overall"),
                    **{k: score(k) for k in SUBSCORES}, "weakest": cell("weakest"), "notes": cell("notes")})
    return out


def mock_rows(parsed: list[dict]) -> list[dict]:
    """The last row per date and source (a same-day retake replaces the earlier one; an `official` row never
    replaces a practice row), by date, file order within a day — the rows every mock rule runs on."""
    last: dict[tuple[str, str], dict] = {}
    for r in parsed:
        last.pop((r["date"], r["source"]), None)
        last[(r["date"], r["source"])] = r
    return sorted(last.values(), key=lambda r: r["date"])


def mock_dates(rows: list[dict], practice_only: bool = False) -> list[tuple[str, int]]:
    """(date, overall) per date, oldest first; two sources on one day count once, with the lower overall."""
    by: dict[str, int] = {}
    for r in rows:
        if not (practice_only and r["source"] == OFFICIAL):
            by[r["date"]] = min(by.get(r["date"], r["overall"]), r["overall"])
    return sorted(by.items())


def has_subscores(r: dict) -> bool:
    return all(r[s] is not None for s in SUBSCORES)


def mock_focus(rows: list[dict]) -> dict:
    """Next week's extra drill slot: {"subscore", "folders", "reason"}. 1. The lowest subscore of the latest row
    that has all four, if it is ≤ SUBSCORE_DAYS before the latest row — a tie goes to the one that dropped most
    since the previous row with subscores, then to SUBSCORES order. 2. Else the latest row's `weakest`.
    3. Else vocabulary (subscore None): `no mocks` without rows, `no weakest` when the latest has neither."""
    if not rows:
        return {"subscore": None, "folders": [], "reason": "no mocks"}
    latest, full = rows[-1], [r for r in rows if has_subscores(r)]
    if full and (date.fromisoformat(latest["date"]) - date.fromisoformat(full[-1]["date"])).days <= SUBSCORE_DAYS:
        r, prev = full[-1], full[-2] if len(full) > 1 else None
        low = [s for s in SUBSCORES if r[s] == min(r[s] for s in SUBSCORES)]
        if len(low) > 1 and prev:
            drop = {s: prev[s] - r[s] for s in low}
            low = [s for s in low if drop[s] == max(drop.values())]
        return {"subscore": low[0], "folders": FOLDERS[low[0]], "reason": f"subscores of {r['date']}"}
    if latest["weakest"]:
        return {"subscore": latest["weakest"], "folders": FOLDERS[latest["weakest"]], "reason": "weakest column"}
    return {"subscore": None, "folders": [], "reason": "no weakest"}


def mock_verdict(rows: list[dict]) -> tuple[str, Optional[int]]:
    """Book the real test yet? (verdict, gap). `Goal reached` on any official row ≥ TARGET; the rest on the
    practice dates of mock_dates(): `Book the real test` when the last two are ≥ TARGET, `one more ≥ 120 to
    book` when only the last is (or there is only one), else `keep going` with the gap TARGET − last overall."""
    if any(r["source"] == OFFICIAL and r["overall"] >= TARGET for r in rows):
        return "Goal reached", None
    dates = mock_dates(rows, practice_only=True)
    if not dates:
        return "keep going", None
    if dates[-1][1] < TARGET:
        return "keep going", TARGET - dates[-1][1]
    if len(dates) > 1 and dates[-2][1] >= TARGET:
        return "Book the real test", None
    return f"one more ≥ {TARGET} to book", None


def mocks_report(mocks: list[dict], history: list[dict], today: date) -> dict:
    """The `mocks` key of build(): the de-duplicated rows (+ `vocab`, the DET range of the latest reliable level
    test on or before the mock), the chart series (one point per date), the trend of the last two dates (the
    level_history() rule), `overdue`, the focus and the verdict. Raises ValueError on a bad row."""
    rows = mock_rows(parse_mocks(mocks))
    reliable = [h for h in history if h["reliable"] and h["det_low"] is not None]
    for r in rows:
        prior = [h for h in reliable if h["date"] <= r["date"]]
        r["vocab"] = det_range(prior[-1]["det_low"], prior[-1]["det_high"]) if prior else ""
    dates = mock_dates(rows)
    last = [o for _, o in dates[-2:]]
    trend = "" if len(last) < 2 else "up" if last[1] > last[0] else "down" if last[1] < last[0] else "flat"
    overdue = not rows or date.fromisoformat(rows[-1]["date"]) < today - timedelta(days=MOCK_DAYS)
    verdict, gap = mock_verdict(rows)
    return {"rows": rows, "series": [{"date": d, "overall": o} for d, o in dates], "trend": trend,
            "overdue": overdue, "focus": mock_focus(rows), "verdict": verdict, "gap": gap}


def listening(attempts: list[dict], today: date, task: str = "listen-and-type", days: int = KIND_DAYS) -> dict:
    """The dictation side of the report (#16): `attempts` = rows of `task`, `kinds` = the error kinds of the last
    `days` days as counts (EVENT_KINDS minus hit), `days`."""
    rows = [r for r in attempts if r.get("task") == task]
    since = (today - timedelta(days=days)).isoformat()
    kinds = {k: 0 for k in EVENT_KINDS if k != "hit"}
    for r in rows:
        if r["date"] >= since:
            for _, kind in parse_events(r.get("events", "")):
                if kind in kinds:
                    kinds[kind] += 1
    return {"attempts": len(rows), "kinds": kinds, "days": days}


def build(sessions: list[dict], levels: list[dict], subbands: list[Subband], today: Optional[date] = None,
          mocks: Optional[list[dict]] = None, b_of: Optional[dict[str, float]] = None,
          attempts: Optional[list[dict]] = None, index: Optional[dict[str, dict]] = None,
          my_words: Optional[list[dict]] = None, plan: Optional[dict] = None) -> dict:
    """The report: `theta_test` from the last reliable session (learn.theta_history on `sessions`, word
    difficulties from `b_of` = Bank.b, else the middle of each block's sub-band), `theta`/`se` = that posterior
    updated by the scored drill attempts since it (`attempts` = practice/attempts.csv rows, #16) — level,
    frontier and the DET estimate come from it — `theta_listen`/`se_listen` from the dictation attempts only,
    the pooled sub-band rows, the word-status counts (drill events merged, `index` for their sub-band), the
    listening line, the chart series, the priority pool (`pool`: learn.pool_counts of learn.priority_pool on
    `my_words` = every my-words row, plus `done` by cards / by practice; #13, needs `index`) and the mock tests
    (mocks_report() on `mocks`, the store.load_mocks() rows; None = no rows) and the schedule (`plan` = a
    plan.today_plan() dict, #19; None = no plan file). `anki` stays None; scripts/report.py fills it from
    anki_stats()."""
    by = {sb.name: sb for sb in subbands}
    attempts, my_words = attempts or [], my_words or []
    scores = learn.subband_scores(sessions, subbands)
    thetas = learn.theta_history(sessions, subbands, b_of)
    test = learn.current_theta(thetas)
    now = learn.drill_theta(thetas, attempts)
    listen = learn.drill_theta(thetas, attempts, ("listen-and-type",))
    theta, se = now if now else (None, None)
    level, front = learn.frontier(theta, subbands)
    history, trend = learn.level_history(levels)
    reliable = [h for h in history if h["reliable"]]
    sb = by.get(level) if level else None
    stats = learn.word_stats(sessions, subbands, attempts, index)
    rows = [{"subband": s["subband"], "cefr": by[s["subband"]].cefr,
             "det": det_range(by[s["subband"]].det_low, by[s["subband"]].det_high), **s} for s in scores]
    today = today or date.today()
    return {"generated": today.isoformat(),
            "tests": len(history), "reliable_tests": len(reliable),
            "no_level": sum(1 for h in reliable if h["level"] is None),      # reliable, but nothing mastered
            "level": level, "frontier": front, "last_level": reliable[-1]["level"] if reliable else None,
            "cefr": sb.cefr if sb else None, "det_low": sb.det_low if sb else None,
            "det_high": sb.det_high if sb else None, "trend": trend,
            "theta": theta, "se": se, "theta_test": test[0] if test else None,
            "theta_listen": listen[0] if listen else None, "se_listen": listen[1] if listen else None,
            "det_estimate": irt.det_estimate(theta, subbands) if now else None,
            "det_range": list(irt.det_range(theta, se, subbands)) if now else None,
            "thetas": thetas, "theta_series": theta_series(thetas),
            "subbands": rows, "counts": learn.status_counts(stats),
            "listening": listening(attempts, today),
            "pool": {**learn.pool_counts(learn.priority_pool(stats, learn.open_my_words(my_words), index or {}, front)),
                     "done": learn.done_counts(my_words)},
            "series": level_series(history, by), "anki": None,
            "mocks": mocks_report(mocks or [], history, today), "plan": plan}


def det_line(det: int, rng) -> str:
    """`DET ≈ 97 (95–100)`."""
    return f"DET ≈ {det} ({rng[0]}–{rng[1]})"


def now_line(r: dict) -> str:
    """`Level 4k-a (B2) · DET ≈ 97 (95–100) · θ 8.13 ± 0.34 · frontier 5k-a · trend up · 3 tests (3 reliable)`
    (`· last test 3k-b` when the levels.csv row of the last reliable test says something else)."""
    parts = [f"Level {r['level']} ({r['cefr']}) · {det_line(r['det_estimate'], r['det_range'])}" if r["level"]
             else "No level yet"]
    if r["theta"] is not None:
        parts.append(f"θ {r['theta']:.2f} ± {r['se']:.2f}")
    parts.append(f"frontier {r['frontier']}")
    if r["trend"]:
        parts.append(f"trend {r['trend']}")
    parts.append(f"{r['tests']} test{'s' if r['tests'] != 1 else ''} ({r['reliable_tests']} reliable)")
    if r["last_level"] != r["level"]:
        parts.append(f"last test {r['last_level'] or 'no level'}")
    return " · ".join(parts)


def pool_line(r: dict) -> str:
    """`Priority pool: 23 words (my-words 9 · repeat 4 · missed 7 · shaky 3) · frontier 480 · my-words done: 3 by
    cards, 1 by practice` — the numbers the practice page shows (#13)."""
    p = r["pool"]
    tiers = " · ".join(f"{k} {p[k]}" for k in learn.PRIORITY)
    return (f"Priority pool: {p['total']} word{'s' if p['total'] != 1 else ''} ({tiers}) · frontier {p['frontier']}"
            f" · my-words done: {p['done']['cards']} by cards, {p['done']['practice']} by practice")


def listening_line(r: dict) -> str:
    """`θ_listen = 7.90 ± 0.33 (vocabulary θ = 8.13) · 12 dictations · errors in the last 14 days: hearing 3 ·
    spelling 1 · form 0 · vocabulary 2`; before the first dictation `_No dictation yet._`; without a reliable
    test the θ part is left out."""
    li = r["listening"]
    if not li["attempts"]:
        return "_No dictation yet — the Listen and Type drill feeds this line._"
    parts = []
    if r["theta_listen"] is not None:
        parts.append(f"θ_listen = {r['theta_listen']:.2f} ± {r['se_listen']:.2f} (vocabulary θ = {r['theta_test']:.2f})")
    parts.append(f"{li['attempts']} dictation{'s' if li['attempts'] != 1 else ''}")
    parts.append(f"errors in the last {li['days']} days: " + " · ".join(f"{k} {n}" for k, n in li["kinds"].items()))
    return " · ".join(parts)


def table(header: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def theta_label(p: dict, series: list[dict]) -> str:
    """`15 Sep`, with the time (`15 Sep 21:44`) when the day has more than one session on the chart."""
    day = date.fromisoformat(p["date"]).strftime("%-d %b")
    return f"{day} {p['started'][11:16]}" if sum(1 for q in series if q["date"] == p["date"]) > 1 else day


def chart(series: list[dict], subbands: list[Subband]) -> str:
    """Mermaid xychart of the θ series: x = one label per reliable session, y = θ on the band index (0–12);
    the second line is the goal, the bottom of the first sub-band at DET TARGET."""
    goal = next((sb for sb in subbands if sb.det_low >= TARGET), subbands[-1])
    labels = ", ".join(f'"{theta_label(p, series)}"' for p in series)
    thetas = ", ".join(f"{p['theta']:.2f}" for p in series)
    return "\n".join(["```mermaid", "xychart-beta",
                      f'    title "Ability θ per test (0–1 = {subbands[0].name} … {len(subbands) - 1}–{len(subbands)} = '
                      f'{subbands[-1].name}; {goal.order - 1} = {goal.cefr} / DET {TARGET})"',
                      f"    x-axis [{labels}]", f'    y-axis "θ" 0 --> {len(subbands)}',
                      f"    line [{thetas}]",
                      f"    line [{', '.join([str(goal.order - 1)] * len(series))}]", "```"])


def theta_lines(thetas: list[dict]) -> list[str]:
    """One line per finished session: `- 15 Sep 21:44 · θ = 6.77 ± 0.25 → 4k-a (level 3k-b), DET ≈ 80 (77–83)`."""
    out = []
    for h in thetas:
        when = date.fromisoformat(h["date"]).strftime("%-d %b %Y") + " " + h["started"][11:16]
        level = f"level {h['level']}" if h["level"] else "no level"
        out.append(f"- {when} · θ = {h['theta']:.2f} ± {h['se']:.2f} → {h['frontier']} ({level}), "
                   f"{det_line(h['det'], h['det_range'])}" + ("" if h["reliable"] else " · unreliable"))
    return out


def mock_chart(series: list[dict]) -> str:
    """Mermaid xychart of the overall score per date (`09-20` labels) with a flat TARGET line for the gap."""
    lo = min(60, min(p["overall"] for p in series) // 10 * 10)
    labels = ", ".join(f'"{p["date"][5:]}"' for p in series)
    return "\n".join(["```mermaid", "xychart-beta", '    title "Mock tests: overall"', f"    x-axis [{labels}]",
                      f'    y-axis "DET" {lo} --> {SCALE[-1]}', f"    line [{', '.join(str(p['overall']) for p in series)}]",
                      f"    line [{', '.join([str(TARGET)] * len(series))}]", "```"])


def mock_lines(m: dict, frontier: str) -> list[str]:
    """The *Mock tests* section body: the chart and the table when there are rows (official rows in bold, `←`
    on the lowest subscore of a row that has all four), then the trend (+ `mock overdue`), the focus with its
    reason and the booking verdict."""
    md = []
    if m["rows"]:
        lines = []
        for r in m["rows"]:
            low = min(r[s] for s in SUBSCORES) if has_subscores(r) else None
            cells = [r["date"], r["source"], r["overall"],
                     *["" if r[s] is None else f"{r[s]} ←" if r[s] == low else r[s] for s in SUBSCORES],
                     r["weakest"], r["vocab"]]
            lines.append([f"**{c}**" if c != "" and r["source"] == OFFICIAL else c for c in cells])
        md += [mock_chart(m["series"]), "", table(["Date", "Source", "Overall", *[s.capitalize() for s in SUBSCORES],
                                                   "Weakest", "Vocab"], lines), ""]
    else:
        md += ["_No mock yet — take the free practice test and type it as row 1 of vocab/tests/mocks.csv._", ""]
    f = m["focus"]
    focus = f"{f['subscore'].capitalize()} → {', '.join(f['folders'])}" if f["subscore"] else f"vocabulary → {frontier}"
    verdict = m["verdict"] if m["gap"] is None else f"{m['verdict']} (gap {m['gap']})"
    if m["verdict"] in ("Goal reached", "Book the real test"):
        verdict = f"**{verdict}**"
    return md + [f"- Trend: {m['trend'] or DASH}" + (" · mock overdue" if m["overdue"] else ""),
                 f"- Focus next week: {focus} ({f['reason']})", f"- Booking: {verdict}"]


def plan_lines(p: Optional[dict]) -> list[str]:
    """The *Plan* section (#19): the week, the streak, the slide and the projected date, then the gate table."""
    if not p:
        return ["_No plan yet: `python3 scripts/plan.py init --start <Monday>`._"]
    state = "on track" if p["on_track"] else f"late by {p['slide']} wk"
    head = (f"Week **{p['week']}** of {p['weeks']} (from {p['start']}) · streak **{p['streak']}** · {state} · "
            f"projected test date **{p['projected']}**" + ("" if p["on_track"] else f" (target {p['target']})"))
    rows = [[g["subband"], g["week"], g["due_now"] + (f" (was {g['due']})" if g["due_now"] != g["due"] else ""),
             f"passed {g['passed_on']}" if g["passed_on"] else g["status"]] for g in p["gates"]]
    return [head, "", table(["Gate", "Week", "By", "Status"], rows)]


def render_markdown(r: dict, subbands: list[Subband]) -> str:
    """Everything between the markers, HEADING first, in the order fixed in #9 (*Listening*, #16, after
    *Words*), then the *Plan* section of #19 after **Anki** and the *Mock tests* section of #11 last. Ends
    with a newline."""
    md = [HEADING, GENERATED.format(date=r["generated"]), "", "### Now", "", now_line(r), "", "### Sub-bands", ""]
    pct = lambda x: f"{100 * x:.0f} %" if x is not None else DASH                          # noqa: E731
    md.append(table(["Sub-band", "CEFR", "DET", "Blocks", "Known", "Score", "Status"],
                    [[s["subband"], s["cefr"], s["det"], s["blocks"], pct(s["known"]),
                      f"{s['score']:.2f}" if s["score"] is not None else DASH,
                      s["status"] + (" ← frontier" if s["subband"] == r["frontier"] else "")] for s in r["subbands"]]))
    c = r["counts"]
    md += ["", "### Words", "", " · ".join(f"{k} {c[k]}" for k in learn.STATUSES) + f" ({c['seen']} seen)", "",
           pool_line(r), "", "### Listening", "", listening_line(r),
           "", "### Ability over time", ""]
    if r["thetas"]:
        md += theta_lines(r["thetas"]) + [""]
    if r["theta_series"]:
        md += [chart(r["theta_series"], subbands), "",
               table([f"{sb.order - 1}–{sb.order}" for sb in subbands], [[sb.name for sb in subbands]])]
    else:
        md.append("_No reliable test yet — the chart starts with the first one._")
    unreliable = r["tests"] - r["reliable_tests"]
    if unreliable:
        md += ["", f"_Not on the chart: {unreliable} unreliable._"]
    if r["anki"] is not None:
        md += ["", "### Anki", ""]
        md.append(table(["Sub-band", "Cards", "Mature", f"Reviews {REVIEW_DAYS}d", "Lapses"],
                        [[a["subband"], a["cards"], a["mature"], a["reviews"], a["lapses"]] for a in r["anki"]])
                  if r["anki"] else "_No cards tagged with a sub-band yet._")
    md += ["", "### Plan", "", *plan_lines(r.get("plan"))]
    md += ["", "### Mock tests", "", *mock_lines(r["mocks"], r["frontier"])]
    return "\n".join(md) + "\n"


def splice(text: str, generated: str) -> str:
    """`text` with everything strictly between START and END replaced by `generated` (the #7 rule table).
    Both markers missing → a blank line, the markers and the block are appended, the text above untouched.
    One marker missing, a marker repeated, or END before START → ValueError (the script exits 1)."""
    lines = text.split("\n")
    starts = [i for i, l in enumerate(lines) if l == START]
    ends = [i for i, l in enumerate(lines) if l == END]
    block = [START, *generated.strip("\n").split("\n"), END]
    if not starts and not ends:
        head = text if not text or text.endswith("\n") else text + "\n"
        return head + ("\n" if head else "") + "\n".join(block) + "\n"
    if len(starts) != 1 or len(ends) != 1:
        raise ValueError(f"needs exactly one {START} and one {END} line, each alone on its line "
                         f"(found {len(starts)} and {len(ends)})")
    if ends[0] < starts[0]:
        raise ValueError(f"{END} comes before {START}")
    return "\n".join([*lines[: starts[0]], *block, *lines[ends[0] + 1:]])


def anki_stats(conn: sqlite3.Connection, subbands: list[Subband], now: Optional[datetime] = None) -> list[dict]:
    """Per sub-band, from a copy of Anki's collection.anki2: cards whose note carries the sub-band as a tag
    (export_anki() writes `<subband> <reason>`; Anki splits it into two tags), of which mature, reviews in the
    last REVIEW_DAYS days and lapses. Only sub-bands with cards, in subbands.csv order."""
    since = int(((now or datetime.now()) - timedelta(days=REVIEW_DAYS)).timestamp() * 1000)
    reviews = dict(conn.execute("SELECT cid, COUNT(*) FROM revlog WHERE id >= ? GROUP BY cid", (since,)))
    names = {sb.name for sb in subbands}
    agg: dict[str, dict] = {}
    for cid, tags, ivl, lapses in conn.execute("SELECT c.id, n.tags, c.ivl, c.lapses FROM cards c JOIN notes n ON n.id = c.nid"):
        for tag in set(tags.split()) & names:
            a = agg.setdefault(tag, {"subband": tag, "cards": 0, "mature": 0, "reviews": 0, "lapses": 0})
            a["cards"] += 1
            a["mature"] += ivl >= MATURE
            a["reviews"] += reviews.get(cid, 0)
            a["lapses"] += lapses
    return [agg[sb.name] for sb in subbands if sb.name in agg]


def check(sessions: list[dict], levels: list[dict], results: list[dict]) -> list[str]:
    """Disagreements between the CSV views and the session JSON (a hand-edited CSV): one line each, empty
    when everything matches. levels.csv: one row per finished session with the same level, blocks and
    reliable flag; results.csv: one row per finished block with the same hits and false alarms."""
    out = []
    by_level = {r["session"]: r for r in levels}
    by_result: dict[str, list[dict]] = {}
    for r in results:
        by_result.setdefault(r["session"], []).append(r)
    for s in sessions:
        if not s.get("finished"):
            continue
        row, res = by_level.get(s["id"]), s["result"]
        if row is None:
            out.append(f"{s['id']}: no levels.csv row")
        else:
            want = {"level": res["level"] or "", "blocks": str(res["blocks"]), "reliable": str(int(res["reliable"]))}
            for k, v in want.items():
                if row[k] != v:
                    out.append(f"{s['id']}: levels.csv {k} = {row[k]!r}, session says {v!r}")
        blocks = [b for b in s["blocks"] if b["pos"] >= len(b["items"])]
        rows = by_result.get(s["id"], [])
        if len(rows) != len(blocks):
            out.append(f"{s['id']}: {len(rows)} results.csv rows, session has {len(blocks)} finished blocks")
        for b, r in zip(blocks, rows):
            if (r["subband"], r["hits"], r["false_alarms"]) != (b["subband"], str(b["hits"]), str(b["false_alarms"])):
                out.append(f"{s['id']} block {b['no']}: results.csv says {r['subband']} {r['hits']}/{r['false_alarms']}, "
                           f"session says {b['subband']} {b['hits']}/{b['false_alarms']}")
    known = {s["id"] for s in sessions}
    out += [f"{r['session']}: levels.csv row without a session file" for r in levels if r["session"] not in known]
    return out
